version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install aws-sam-cli
  pre_build:
    commands:
      - sam validate
      - sam build
  build:
    commands:
      - sam package \
          --s3-bucket $S3_BUCKET \
          --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml
