version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install aws-sam-cli
  pre_build:
    commands:
      - sam validate
      - sam build
  build:
    commands:
      - echo "S3_BUCKET=$S3_BUCKET"
      - sam package --s3-bucket $S3_BUCKET --output-template-file packaged.yaml
  post_build:
    commands:
      - sam deploy \
          --template-file packaged.yaml \
          --stack-name sam-app-stack \
          --capabilities CAPABILITY_IAM \
          --region us-east-1 \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset
   

artifacts:
  files:
    - packaged.yaml

